const data = 
[{
  "title":"Komodo",
  "artist":"Mauro Picotto",
  "publish":2000,
  "chart":"4 (A,CH)",
  "cover":"./Img/Komodo.png",
  "likes":0,
  "ID":1,
},
  {
  "title":"Almost Home",
  "artist":"Moby",
  "publish":2013,
  "chart":"5 (D)",
  "cover":"./Img/Moby.png",
  "likes":0,
  "ID":2,
  },
  {
    "title":"River flows in you",
    "artist":"Jasper Forks",
    "publish":2010,
    "chart":"45 (D)",
    "cover":"./Img/River_flows_in_you.png",
    "likes":0,
    "ID":3,
  },
  {
    "title":"Lamour Toujour`s",
    "artist":"Gigi D´Agostino",
    "publish":2001,
    "chart":"3 (D,A)",
    "cover":"./Img/Toujours.png",
    "likes":0,
    "ID":4,
  },
  {
    "title":"L´Esperanza",
    "artist":"Topmodelz",
    "publish":2001,
    "chart":"72 (D)",
    "cover":"./Img/Topmodelz.png",
    "likes":0,
    "ID":5,
  },
  {
    "title":"Sky and Sand",
    "artist":"Paul Kalkbrenner",
    "publish":2008,
    "chart":"29 (D)",
    "cover":"./Img/Sky&Sand.png",
    "likes":0,
    "ID":6,
}]
;